import "./styles/global.css";

export const metadata = {
  title: "Dummy Pet App",
  description: "This is the dashboard of my application.Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body >
        {children}
      </body>
    </html>
  );
}
